POST http://127.0.0.1:8000/api/v1/a
Accept: application/json
Content-Type: application/json

{
    "email":"cristian@gmail.com",
    "password": "123"
}


###PERFIL
GET http://127.0.0.1:8000/api/v1/auth/profile
Accept:  application/json
Authorization: Bearer 13|pkcrmi1Mzyp0wXpqcgezcSynz96gM0mpldfuF0Rqdf1e5cb2


###SALIR
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept:  application/json
Authorization: Bearer 13|pkcrmi1Mzyp0wXpqcgezcSynz96gM0mpldfuF0Rqdf1e5cb2
